### ISSUE TITLE
Uncaught TypeError: UID is not a constructor

### ISSUE THREAD

**Issue by pstuashiqcse** [alexanderschau/uniquebrowserid#1]
I have implemented the following code and getting error:

const UID = require('uniquebrowserid')

let id = new UID().completeID()
console.log(id)

Error: Uncaught TypeError: UID is not a constructor

**Comment by alexanderschau** [comment]
Did you run it in your browser? If so, can you give me more details about your coding environment (e.g. React/Vue/Angular)?
